name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn client:test
      - name: Build frontend
        run: yarn client:build
        env:
          VITE_API_ENDPOINT: ${{ secrets.API_ENDPOINT }}


#      # Save build artifacts for deployment
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: frontend-artifacts
#          path: ./packages/frontend/dist
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      # Get build artifacts
#      - name: Download frontend artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: frontend-artifacts
#          path: ./dist
#
#      - name: Configure AWS credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: eu-central-1
#
#      - name: Sync build data to S3
#        run: aws s3 sync ./dist ${{ secrets.AWS_S3_BUCKET }}
